# Generated by Django 4.1.2 on 2022-10-12 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='media/kurs/')),
                ('max_student', models.IntegerField()),
                ('course_time', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('tgid', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurs.kurs')),
            ],
        ),
    ]
